const AccountName = "vtexlab";

const VtexToken = "FJMDPBEELQCQLPWCHMBSYPOCEGUARPDVPDZMWYDMXIUVTONXGKAAQRUPUKZJHDNVNHBHPJFIJOVQVTIQTWTHOCEYIKSMZUETUYHMMFHXERQCVETACIPLJGHKCDZFRTJP";

const VtexKey = "vtexappkey-vtexlab-IRATSK";


export {AccountName, VtexKey, VtexToken}